# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI 01-07\AlarmsConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from playsound import playsound
playsound('audio.mp3')


class Ui_AlarmsConfig(object):
    def Inc(self):
        x=self.lcdNumber_8.intValue()
        if x<55 :
            x=self.lcdNumber_8.intValue()
            x=x+1
            self.lcdNumber_8.setProperty("value", x)
            self.lcdNumber_8.display(x)

            
    def Dec(self):
        x=self.lcdNumber_8.intValue()
        if x>10 :
            x=x-1
            self.lcdNumber_8.setProperty("value", x)
            self.lcdNumber_8.display(x)
    def Inc2(self):
        x=self.lcdNumber_5.intValue()
        if x<15 :
            x=self.lcdNumber_5.intValue()
            x=x+1
            self.lcdNumber_5.setProperty("value", x)
            self.lcdNumber_5.display(x)

            
    def Dec2(self):
        x=self.lcdNumber_5.intValue()
        if x>5 :
            x=x-1
            self.lcdNumber_5.setProperty("value", x)
            self.lcdNumber_5.display(x)        
    def Inc3(self):
        x=self.lcdNumber.intValue()
        if x<60 :
            x=self.lcdNumber.intValue()
            x=x+1
            self.lcdNumber.setProperty("value", x)
            self.lcdNumber.display(x)

            
    def Dec3(self):
        x=self.lcdNumber.intValue()
        if x>15 :
            x=x-1
            self.lcdNumber.setProperty("value", x)
            self.lcdNumber.display(x)
    def Inc4(self):
        x=self.lcdNumber_6.intValue()
        if x<40 :
            x=self.lcdNumber_6.intValue()
            x=x+1
            self.lcdNumber_6.setProperty("value", x)
            self.lcdNumber_6.display(x)

            
    def Dec4(self):
        x=self.lcdNumber_6.intValue()
        if x>37 :
            x=x-1
            self.lcdNumber_6.setProperty("value", x)
            self.lcdNumber_6.display(x)
    def Inc5(self):
        x=self.lcdNumber_7.intValue()
        if x<40 :
            x=self.lcdNumber_7.intValue()
            x=x+1
            self.lcdNumber_7.setProperty("value", x)
            self.lcdNumber_7.display(x)

            
    def Dec5(self):
        x=self.lcdNumber_7.intValue()
        if x>37 :
            x=x-1
            self.lcdNumber_7.setProperty("value", x)
            self.lcdNumber_7.display(x)                
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("QFrame {\n"
"     background: linear-gradient(90deg, #22c1c3, #fdbb2d);  \n"
"\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(690, 490, 91, 91))
        self.pushButton.setStyleSheet("image: url(:/newPrefix/New folder/back_light.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda:Form.close())
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(440, 190, 41, 21))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 161, 61))
        self.label_4.setObjectName("label_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_5.setGeometry(QtCore.QRect(350, 180, 81, 41))
        self.lcdNumber_5.setProperty("intValue", 5)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 191, 41))
        self.label_5.setObjectName("label_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 180, 71, 71))
        self.pushButton_10.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.Dec2)

        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(500, 170, 71, 71))
        self.pushButton_11.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.Inc2)

        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 80, 71, 71))
        self.pushButton_12.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.Inc)

        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 90, 71, 71))
        self.pushButton_13.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.Dec)

        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_8.setGeometry(QtCore.QRect(350, 100, 81, 41))
        self.lcdNumber_8.setProperty("intValue", 10)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(450, 110, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(70, 100, 161, 61))
        self.label_12.setObjectName("label_12")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(350, 280, 80, 40))
        self.lcdNumber.setProperty("intValue", 15)

        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 270, 71, 71))
        self.pushButton_2.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Dec3)

        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(70, 270, 161, 61))
        self.label_13.setObjectName("label_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 270, 71, 71))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Inc3)

        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(440, 290, 41, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(70, 370, 161, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(70, 440, 161, 61))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(70, 520, 161, 61))
        self.label_17.setObjectName("label_17")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 350, 71, 71))
        self.pushButton_4.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 350, 71, 71))
        self.pushButton_5.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setGeometry(QtCore.QRect(350, 360, 80, 40))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(250, 440, 71, 71))
        self.pushButton_14.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.Dec4)

        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(500, 440, 71, 71))
        self.pushButton_15.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.Inc4)

        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_6.setGeometry(QtCore.QRect(350, 450, 80, 40))
        self.lcdNumber_6.setProperty("intValue", 37)

        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(250, 520, 71, 71))
        self.pushButton_16.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.Dec5)

        self.pushButton_17 = QtWidgets.QPushButton(self.frame)
        self.pushButton_17.setGeometry(QtCore.QRect(500, 520, 71, 71))
        self.pushButton_17.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.Inc5)

        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_7.setGeometry(QtCore.QRect(350, 530, 80, 40))
        self.lcdNumber_7.setProperty("intValue", 37)

        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(450, 370, 41, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(450, 460, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(450, 530, 41, 21))
        self.label_20.setObjectName("label_20")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">cmH2O</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Low Pressure</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Alarm Threshold</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Alarms</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">cmH2O</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">High Pressure</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Alarm Threshold</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Apnea Backup</span></p><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\"> Ventilation</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">sec</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Leakage</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Low Source O2</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Low Source Air</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">%</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">psi</span></p></body></html>"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">psi</span></p></body></html>"))
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_AlarmsConfig()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
