# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI 01-07\GraphPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from InspirationConfig import *
from IERatioConfig import   *
from TidalVolumeConfig import *
from ExpirationConfig import *
from RRConfig import *
from OxygeneConfig import *
from TriggerPressureConfig import *
from FlowConfig import *
from DefaultPage import *
from SettingsPage import *
from LoadPatientData import *
from AlarmsConfig import *
from PressureConfig import *
from PyQt5.QtWidgets import QWidget
import sys
from PyQt5 import QtWidgets as qtw
from PyQt5 import QtGui as qtg
from PyQt5 import QtCore as qtc
from PyQt5.QtCore import QFileInfo, QSettings
from PyQt5.QtWidgets import qApp

class Ui_GraphPage(QWidget):
    def CurrentModes(self):
        cb1=str(self.comboBox.currentIndex())
        print(cb1)
        cb2=str(self.stackedWidget.currentIndex())
        print(cb2)

    def ChooseModes(self):
        self.stackedWidget.setCurrentIndex(self.comboBox.currentIndex())


            

        
    def AlarmsConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_AlarmsConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def LoadPatientData(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_LoadPatientData()
        self.ui.setupUi(self.window)
        self.window.show()
    def PressureConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_PressureConfig()
        self.ui.setupUi(self.window)
        self.window.show()        
    def InspirationConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_InspirationConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def IERatioConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_IERatioConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def TidalVolumeConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui =Ui_TidalVolumeConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def ExpirationConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_ExpirationConfig()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def RRConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_RRConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def TriggerPressureConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_TriggerPressureConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def OxygeneConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_OxygeneConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def FlowConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_FlowConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def SettingsPage(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_SettingsPage()
        self.ui.setupUi(self.window)
        self.window.show()
    def DefaultPage (self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_DefaultPage ()
        self.ui.setupUi(self.window)
        self.window.show()    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1110, 160, 120, 120))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(10, 242, 251, 255), stop:1 rgba(224, 6, 159, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/trigger_light.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.DefaultPage)
        self.pushButton.clicked.connect(lambda:Form.close())



        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1110, 310, 120, 120))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 199, 0, 255), stop:1 rgba(192, 5, 67, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/default_view_light.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1110, 460, 120, 120))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/New folder/start_light.png);\n"
"\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:1, y1:0, x2:0.995, y2:1, stop:0 rgba(218, 218, 218, 255), stop:0.305419 rgba(0, 7, 11, 255), stop:0.935961 rgba(2, 11, 18, 255), stop:1 rgba(240, 240, 240, 255));\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView = PlotWidget(Form)
        self.graphicsView.setGeometry(QtCore.QRect(260, 60, 831, 191))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = PlotWidget(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(260, 260, 831, 191))
        self.graphicsView_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = PlotWidget(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(260, 460, 831, 191))
        self.graphicsView_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(283, 70, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(283, 270, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(283, 470, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 71, 21))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(170, 110, 51, 41))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 520, 31, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 380, 51, 21))
        self.label_12.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_12.setObjectName("label_12")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:10px;\n"
"border:solid None rgb(255,255,255);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(50, 110, 41, 41))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 210, 41, 20))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(170, 520, 51, 31))
        self.label_14.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_14.setObjectName("label_14")
        self.Trigger = QtWidgets.QPushButton(self.widget)
        self.Trigger.setGeometry(QtCore.QRect(1110, 20, 120, 120))
        self.Trigger.setStyleSheet("\n"
"QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/screen_light.png);\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: green; }\n"
"")
        self.Trigger.setText("")
        self.Trigger.setObjectName("Trigger")
        self.Trigger.clicked.connect(self.LoadPatientData)

        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(160, 10, 111, 41))
        self.comboBox.setMaximumSize(QtCore.QSize(111, 41))
        self.comboBox.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/New folder/lungs--publicdomainvectors-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/New folder/22675800.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        self.comboBox.addItem(icon, "")
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem(icon1, "")
        self.comboBox.currentTextChanged.connect(self.ChooseModes)


        self.enable = QtWidgets.QPushButton(self.widget)
        self.enable.setGeometry(QtCore.QRect(160, 60, 101, 41))
        self.enable.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.enable.setObjectName("enable")
        self.enable.clicked.connect(self. ChooseModes)

        

        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(40, 20, 101, 31))
        self.label_22.setObjectName("label_22")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(920, 20, 161, 22))
        self.dateTimeEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dateTimeEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setDate(QtCore.QDate(2021, 7, 4))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 290, 91, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(120, 290, 91, 51))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(-10, 410, 91, 51))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(-10, 150, 91, 51))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(120, 150, 91, 51))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(-10, 560, 91, 51))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(120, 560, 91, 51))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(-20, 280, 91, 61))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setGeometry(QtCore.QRect(70, 300, 16, 21))
        self.label_26.setObjectName("label_26")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(-80, 660, 1171, 141))
        self.stackedWidget.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.VCV = QtWidgets.QWidget()
        self.VCV.setObjectName("VCV")


        self.pushButton_14 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_14.setGeometry(QtCore.QRect(990, 11, 120, 121))
        self.pushButton_14.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.TidalVolumeConfig)

        self.label_40 = QtWidgets.QLabel(self.VCV)
        self.label_40.setGeometry(QtCore.QRect(180, 20, 41, 16))
        self.label_40.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.VCV)
        self.label_41.setGeometry(QtCore.QRect(860, 60, 101, 61))
        self.label_41.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.VCV)
        self.label_42.setGeometry(QtCore.QRect(560, 60, 101, 61))
        self.label_42.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_42.setObjectName("label_42")
        self.pushButton_18 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_18.setGeometry(QtCore.QRect(850, 11, 120, 120))
        self.pushButton_18.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.clicked.connect(self.FlowConfig)
        self.label_43 = QtWidgets.QLabel(self.VCV)
        self.label_43.setGeometry(QtCore.QRect(320, 20, 41, 16))
        self.label_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.label_51 = QtWidgets.QLabel(self.VCV)
        self.label_51.setGeometry(QtCore.QRect(920, 20, 41, 16))
        self.label_51.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_51.setObjectName("label_51")
        self.label_44 = QtWidgets.QLabel(self.VCV)
        self.label_44.setGeometry(QtCore.QRect(590, 20, 41, 31))
        self.label_44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.VCV)
        self.label_45.setGeometry(QtCore.QRect(260, 50, 101, 71))
        self.label_45.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.VCV)
        self.label_46.setGeometry(QtCore.QRect(740, 20, 71, 31))
        self.label_46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.VCV)
        self.label_47.setGeometry(QtCore.QRect(410, 50, 101, 71))
        self.label_47.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_47.setObjectName("label_47")
        self.pushButton_8 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 10, 120, 121))
        self.pushButton_8.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.ExpirationConfig)
        self.pushButton_19 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_19.setGeometry(QtCore.QRect(710, 10, 120, 120))
        self.pushButton_19.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(self.IERatioConfig)

        self.label_53 = QtWidgets.QLabel(self.VCV)
        self.label_53.setGeometry(QtCore.QRect(1030, 20, 41, 31))
        self.label_53.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_53.setObjectName("label_53")
        self.pushButton_20 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_20.setGeometry(QtCore.QRect(110, 10, 120, 120))
        self.pushButton_20.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.InspirationConfig)

        self.label_54 = QtWidgets.QLabel(self.VCV)
        self.label_54.setGeometry(QtCore.QRect(130, 20, 41, 31))
        self.label_54.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_54.setObjectName("label_54")
        self.label_56 = QtWidgets.QLabel(self.VCV)
        self.label_56.setGeometry(QtCore.QRect(260, 20, 51, 21))
        self.label_56.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.VCV)
        self.label_57.setGeometry(QtCore.QRect(120, 60, 101, 61))
        self.label_57.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.VCV)
        self.label_58.setGeometry(QtCore.QRect(430, 20, 51, 21))
        self.label_58.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_58.setObjectName("label_58")
        self.pushButton_21 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_21.setGeometry(QtCore.QRect(400, 10, 120, 120))
        self.pushButton_21.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(self.OxygeneConfig)

        self.label_59 = QtWidgets.QLabel(self.VCV)
        self.label_59.setGeometry(QtCore.QRect(720, 60, 101, 61))
        self.label_59.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.VCV)
        self.label_60.setGeometry(QtCore.QRect(1000, 60, 101, 61))
        self.label_60.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_60.setObjectName("label_60")
        self.pushButton_22 = QtWidgets.QPushButton(self.VCV)
        self.pushButton_22.setGeometry(QtCore.QRect(550, 10, 120, 120))
        self.pushButton_22.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.clicked.connect(self.RRConfig)
        
        self.label_61 = QtWidgets.QLabel(self.VCV)
        self.label_61.setGeometry(QtCore.QRect(860, 20, 51, 21))
        self.label_61.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_61.setObjectName("label_61")
        self.pushButton_22.raise_()
        self.pushButton_14.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.pushButton_21.raise_()
        self.pushButton_8.raise_()
        self.pushButton_20.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_51.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.stackedWidget.addWidget(self.VCV)
        self.PCV = QtWidgets.QWidget()
        self.PCV.setObjectName("PCV")
        self.label_93 = QtWidgets.QLabel(self.PCV)
        self.label_93.setGeometry(QtCore.QRect(240, 50, 101, 71))
        self.label_93.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.PCV)
        self.label_94.setGeometry(QtCore.QRect(990, 20, 51, 21))
        self.label_94.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.PCV)
        self.label_95.setGeometry(QtCore.QRect(390, 50, 101, 71))
        self.label_95.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.PCV)
        self.label_96.setGeometry(QtCore.QRect(110, 20, 41, 31))
        self.label_96.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.PCV)
        self.label_97.setGeometry(QtCore.QRect(410, 20, 51, 21))
        self.label_97.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_97.setObjectName("label_97")
        self.pushButton_33 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_33.setGeometry(QtCore.QRect(980, 11, 120, 120))
        self.pushButton_33.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_33.clicked.connect(self.FlowConfig)

        self.pushButton_34 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_34.setGeometry(QtCore.QRect(530, 10, 120, 120))
        self.pushButton_34.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_34.clicked.connect(self.RRConfig)

        self.pushButton_35 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_35.setGeometry(QtCore.QRect(230, 10, 120, 121))
        self.pushButton_35.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_35.clicked.connect(self.ExpirationConfig)

        self.label_98 = QtWidgets.QLabel(self.PCV)
        self.label_98.setGeometry(QtCore.QRect(850, 60, 101, 61))
        self.label_98.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.PCV)
        self.label_99.setGeometry(QtCore.QRect(730, 20, 41, 31))
        self.label_99.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.PCV)
        self.label_100.setGeometry(QtCore.QRect(240, 20, 51, 21))
        self.label_100.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.PCV)
        self.label_101.setGeometry(QtCore.QRect(570, 20, 41, 31))
        self.label_101.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.PCV)
        self.label_102.setGeometry(QtCore.QRect(1050, 20, 41, 16))
        self.label_102.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.PCV)
        self.label_103.setGeometry(QtCore.QRect(300, 20, 41, 16))
        self.label_103.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.PCV)
        self.label_104.setGeometry(QtCore.QRect(700, 60, 101, 61))
        self.label_104.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_104.setObjectName("label_104")
        self.label_105 = QtWidgets.QLabel(self.PCV)
        self.label_105.setGeometry(QtCore.QRect(540, 60, 101, 61))
        self.label_105.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_105.setObjectName("label_105")
        self.label_106 = QtWidgets.QLabel(self.PCV)
        self.label_106.setGeometry(QtCore.QRect(990, 60, 101, 61))
        self.label_106.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_106.setObjectName("label_106")
        self.pushButton_36 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_36.setGeometry(QtCore.QRect(90, 10, 120, 120))
        self.pushButton_36.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_36.clicked.connect(self.InspirationConfig)

        self.label_107 = QtWidgets.QLabel(self.PCV)
        self.label_107.setGeometry(QtCore.QRect(100, 60, 101, 61))
        self.label_107.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QLabel(self.PCV)
        self.label_108.setGeometry(QtCore.QRect(870, 20, 71, 31))
        self.label_108.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_108.setObjectName("label_108")
        self.pushButton_37 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_37.setGeometry(QtCore.QRect(380, 10, 120, 120))
        self.pushButton_37.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_37.clicked.connect(self.OxygeneConfig)

        self.pushButton_38 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_38.setGeometry(QtCore.QRect(840, 10, 120, 120))
        self.pushButton_38.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_38.clicked.connect(self.IERatioConfig)

        self.pushButton_40 = QtWidgets.QPushButton(self.PCV)
        self.pushButton_40.setGeometry(QtCore.QRect(690, 10, 120, 121))
        self.pushButton_40.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_40.clicked.connect(self.PressureConfig)

        self.label_111 = QtWidgets.QLabel(self.PCV)
        self.label_111.setGeometry(QtCore.QRect(160, 20, 41, 16))
        self.label_111.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_111.setObjectName("label_111")
        self.pushButton_33.raise_()
        self.pushButton_38.raise_()
        self.pushButton_40.raise_()
        self.pushButton_37.raise_()
        self.pushButton_36.raise_()
        self.pushButton_35.raise_()
        self.label_93.raise_()
        self.label_94.raise_()
        self.label_95.raise_()
        self.label_96.raise_()
        self.label_97.raise_()
        self.pushButton_34.raise_()
        self.label_98.raise_()
        self.label_99.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.label_102.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.label_105.raise_()
        self.label_106.raise_()
        self.label_107.raise_()
        self.label_108.raise_()
        self.label_111.raise_()
        self.stackedWidget.addWidget(self.PCV)
        self.SIMV = QtWidgets.QWidget()
        self.SIMV.setObjectName("SIMV")
        self.label_112 = QtWidgets.QLabel(self.SIMV)
        self.label_112.setGeometry(QtCore.QRect(240, 50, 101, 71))
        self.label_112.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_112.setObjectName("label_112")
        self.label_113 = QtWidgets.QLabel(self.SIMV)
        self.label_113.setGeometry(QtCore.QRect(830, 20, 51, 21))
        self.label_113.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(self.SIMV)
        self.label_114.setGeometry(QtCore.QRect(390, 50, 101, 71))
        self.label_114.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.SIMV)
        self.label_115.setGeometry(QtCore.QRect(110, 20, 41, 31))
        self.label_115.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.SIMV)
        self.label_116.setGeometry(QtCore.QRect(410, 20, 51, 21))
        self.label_116.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_116.setObjectName("label_116")
        self.pushButton_41 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_41.setGeometry(QtCore.QRect(820, 11, 120, 120))
        self.pushButton_41.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_41.clicked.connect(self.FlowConfig)

        self.pushButton_42 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_42.setGeometry(QtCore.QRect(530, 10, 120, 120))
        self.pushButton_42.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_42.setText("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_42.clicked.connect(self.RRConfig)

        self.pushButton_43 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_43.setGeometry(QtCore.QRect(230, 10, 120, 121))
        self.pushButton_43.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_43.setText("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_43.clicked.connect(self.ExpirationConfig)

        self.label_117 = QtWidgets.QLabel(self.SIMV)
        self.label_117.setGeometry(QtCore.QRect(690, 60, 101, 61))
        self.label_117.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_117.setObjectName("label_117")
        self.label_119 = QtWidgets.QLabel(self.SIMV)
        self.label_119.setGeometry(QtCore.QRect(240, 20, 51, 21))
        self.label_119.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QLabel(self.SIMV)
        self.label_120.setGeometry(QtCore.QRect(570, 20, 41, 31))
        self.label_120.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_120.setObjectName("label_120")
        self.label_121 = QtWidgets.QLabel(self.SIMV)
        self.label_121.setGeometry(QtCore.QRect(890, 20, 41, 16))
        self.label_121.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_121.setObjectName("label_121")
        self.label_122 = QtWidgets.QLabel(self.SIMV)
        self.label_122.setGeometry(QtCore.QRect(300, 20, 41, 16))
        self.label_122.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_122.setObjectName("label_122")
        self.label_124 = QtWidgets.QLabel(self.SIMV)
        self.label_124.setGeometry(QtCore.QRect(540, 60, 101, 61))
        self.label_124.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_124.setObjectName("label_124")
        self.label_125 = QtWidgets.QLabel(self.SIMV)
        self.label_125.setGeometry(QtCore.QRect(830, 60, 101, 61))
        self.label_125.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_125.setObjectName("label_125")
        self.pushButton_44 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_44.setGeometry(QtCore.QRect(90, 10, 120, 120))
        self.pushButton_44.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_44.setText("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_44.clicked.connect(self.PressureConfig)

        self.label_126 = QtWidgets.QLabel(self.SIMV)
        self.label_126.setGeometry(QtCore.QRect(100, 60, 101, 61))
        self.label_126.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(self.SIMV)
        self.label_127.setGeometry(QtCore.QRect(710, 20, 71, 31))
        self.label_127.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_127.setObjectName("label_127")
        self.pushButton_45 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_45.setGeometry(QtCore.QRect(380, 10, 120, 120))
        self.pushButton_45.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_45.setText("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_45.clicked.connect(self.OxygeneConfig)

        self.pushButton_46 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_46.setGeometry(QtCore.QRect(680, 10, 120, 120))
        self.pushButton_46.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_46.setText("")
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_46.clicked.connect(self.IERatioConfig)

        self.pushButton_47 = QtWidgets.QPushButton(self.SIMV)
        self.pushButton_47.setGeometry(QtCore.QRect(970, 11, 120, 121))
        self.pushButton_47.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_47.setText("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_47.clicked.connect(self.TidalVolumeConfig)

        self.label_128 = QtWidgets.QLabel(self.SIMV)
        self.label_128.setGeometry(QtCore.QRect(1010, 20, 41, 31))
        self.label_128.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.SIMV)
        self.label_129.setGeometry(QtCore.QRect(980, 60, 101, 61))
        self.label_129.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_129.setObjectName("label_129")
        self.label_130 = QtWidgets.QLabel(self.SIMV)
        self.label_130.setGeometry(QtCore.QRect(160, 20, 41, 16))
        self.label_130.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_130.setObjectName("label_130")
        self.pushButton_41.raise_()
        self.pushButton_46.raise_()
        self.pushButton_45.raise_()
        self.pushButton_43.raise_()
        self.pushButton_44.raise_()
        self.label_112.raise_()
        self.label_113.raise_()
        self.label_114.raise_()
        self.label_115.raise_()
        self.label_116.raise_()
        self.pushButton_42.raise_()
        self.label_117.raise_()
        self.label_119.raise_()
        self.label_120.raise_()
        self.label_121.raise_()
        self.label_122.raise_()
        self.label_124.raise_()
        self.label_125.raise_()
        self.label_126.raise_()
        self.label_127.raise_()
        self.pushButton_47.raise_()
        self.label_128.raise_()
        self.label_129.raise_()
        self.label_130.raise_()
        self.stackedWidget.addWidget(self.SIMV)
        self.CPAP = QtWidgets.QWidget()
        self.CPAP.setObjectName("CPAP")
        self.label_132 = QtWidgets.QLabel(self.CPAP)
        self.label_132.setGeometry(QtCore.QRect(880, 20, 51, 21))
        self.label_132.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_132.setObjectName("label_132")
        self.label_133 = QtWidgets.QLabel(self.CPAP)
        self.label_133.setGeometry(QtCore.QRect(380, 50, 101, 71))
        self.label_133.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_133.setObjectName("label_133")
        self.label_134 = QtWidgets.QLabel(self.CPAP)
        self.label_134.setGeometry(QtCore.QRect(220, 20, 51, 31))
        self.label_134.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.CPAP)
        self.label_135.setGeometry(QtCore.QRect(400, 20, 51, 21))
        self.label_135.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_135.setObjectName("label_135")
        self.pushButton_49 = QtWidgets.QPushButton(self.CPAP)
        self.pushButton_49.setGeometry(QtCore.QRect(870, 11, 120, 120))
        self.pushButton_49.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_49.setText("")
        self.pushButton_49.clicked.connect(self.FlowConfig)

        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.CPAP)
        self.pushButton_50.setGeometry(QtCore.QRect(520, 10, 120, 120))
        self.pushButton_50.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_50.setText("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_50.clicked.connect(self.RRConfig)

        self.label_136 = QtWidgets.QLabel(self.CPAP)
        self.label_136.setGeometry(QtCore.QRect(700, 60, 101, 61))
        self.label_136.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_136.setObjectName("label_136")
        self.label_139 = QtWidgets.QLabel(self.CPAP)
        self.label_139.setGeometry(QtCore.QRect(560, 20, 41, 31))
        self.label_139.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_139.setObjectName("label_139")
        self.label_140 = QtWidgets.QLabel(self.CPAP)
        self.label_140.setGeometry(QtCore.QRect(940, 20, 41, 16))
        self.label_140.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_140.setObjectName("label_140")
        self.label_143 = QtWidgets.QLabel(self.CPAP)
        self.label_143.setGeometry(QtCore.QRect(530, 60, 101, 61))
        self.label_143.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_143.setObjectName("label_143")
        self.label_144 = QtWidgets.QLabel(self.CPAP)
        self.label_144.setGeometry(QtCore.QRect(880, 60, 101, 61))
        self.label_144.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_144.setObjectName("label_144")
        self.pushButton_52 = QtWidgets.QPushButton(self.CPAP)
        self.pushButton_52.setGeometry(QtCore.QRect(210, 10, 120, 120))
        self.pushButton_52.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_52.setText("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_52.clicked.connect(self.PressureConfig)

        self.label_145 = QtWidgets.QLabel(self.CPAP)
        self.label_145.setGeometry(QtCore.QRect(220, 60, 101, 61))
        self.label_145.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_145.setObjectName("label_145")
        self.label_146 = QtWidgets.QLabel(self.CPAP)
        self.label_146.setGeometry(QtCore.QRect(720, 20, 71, 31))
        self.label_146.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_146.setObjectName("label_146")
        self.pushButton_53 = QtWidgets.QPushButton(self.CPAP)
        self.pushButton_53.setGeometry(QtCore.QRect(370, 10, 120, 120))
        self.pushButton_53.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_53.setText("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_53.clicked.connect(self.OxygeneConfig)

        self.pushButton_54 = QtWidgets.QPushButton(self.CPAP)
        self.pushButton_54.setGeometry(QtCore.QRect(690, 10, 120, 120))
        self.pushButton_54.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_54.setText("")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_54.clicked.connect(self.IERatioConfig)

        self.label_149 = QtWidgets.QLabel(self.CPAP)
        self.label_149.setGeometry(QtCore.QRect(280, 20, 41, 16))
        self.label_149.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_149.setObjectName("label_149")
        self.pushButton_49.raise_()
        self.pushButton_54.raise_()
        self.pushButton_50.raise_()
        self.pushButton_53.raise_()
        self.pushButton_52.raise_()
        self.label_135.raise_()
        self.label_139.raise_()
        self.label_140.raise_()
        self.label_132.raise_()
        self.label_149.raise_()
        self.label_143.raise_()
        self.label_136.raise_()
        self.label_134.raise_()
        self.label_144.raise_()
        self.label_146.raise_()
        self.label_133.raise_()
        self.label_145.raise_()
        self.stackedWidget.addWidget(self.CPAP)
        self.BiPAP = QtWidgets.QWidget()
        self.BiPAP.setObjectName("BiPAP")
        self.label_150 = QtWidgets.QLabel(self.BiPAP)
        self.label_150.setGeometry(QtCore.QRect(330, 50, 101, 71))
        self.label_150.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(self.BiPAP)
        self.label_151.setGeometry(QtCore.QRect(940, 20, 51, 21))
        self.label_151.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.BiPAP)
        self.label_152.setGeometry(QtCore.QRect(480, 50, 101, 71))
        self.label_152.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_152.setObjectName("label_152")
        self.label_153 = QtWidgets.QLabel(self.BiPAP)
        self.label_153.setGeometry(QtCore.QRect(200, 20, 41, 31))
        self.label_153.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.BiPAP)
        self.label_154.setGeometry(QtCore.QRect(500, 20, 51, 21))
        self.label_154.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_154.setObjectName("label_154")
        self.pushButton_57 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_57.setGeometry(QtCore.QRect(930, 11, 120, 120))
        self.pushButton_57.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_57.setText("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_57.clicked.connect(self.FlowConfig)

        self.pushButton_58 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_58.setGeometry(QtCore.QRect(620, 10, 120, 120))
        self.pushButton_58.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_58.setText("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_58.clicked.connect(self.RRConfig)

        self.pushButton_59 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_59.setGeometry(QtCore.QRect(320, 10, 120, 121))
        self.pushButton_59.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_59.setText("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_59.clicked.connect(self.ExpirationConfig)

        self.label_155 = QtWidgets.QLabel(self.BiPAP)
        self.label_155.setGeometry(QtCore.QRect(800, 60, 101, 61))
        self.label_155.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_155.setObjectName("label_155")
        self.label_157 = QtWidgets.QLabel(self.BiPAP)
        self.label_157.setGeometry(QtCore.QRect(330, 20, 51, 21))
        self.label_157.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(self.BiPAP)
        self.label_158.setGeometry(QtCore.QRect(660, 20, 41, 31))
        self.label_158.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_158.setObjectName("label_158")
        self.label_159 = QtWidgets.QLabel(self.BiPAP)
        self.label_159.setGeometry(QtCore.QRect(1000, 20, 41, 16))
        self.label_159.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_159.setObjectName("label_159")
        self.label_160 = QtWidgets.QLabel(self.BiPAP)
        self.label_160.setGeometry(QtCore.QRect(390, 20, 41, 16))
        self.label_160.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_160.setObjectName("label_160")
        self.label_162 = QtWidgets.QLabel(self.BiPAP)
        self.label_162.setGeometry(QtCore.QRect(630, 60, 101, 61))
        self.label_162.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_162.setObjectName("label_162")
        self.label_163 = QtWidgets.QLabel(self.BiPAP)
        self.label_163.setGeometry(QtCore.QRect(940, 60, 101, 61))
        self.label_163.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_163.setObjectName("label_163")
        self.pushButton_60 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_60.setGeometry(QtCore.QRect(180, 10, 120, 120))
        self.pushButton_60.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_60.setText("")
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_60.clicked.connect(self.InspirationConfig)

        self.label_164 = QtWidgets.QLabel(self.BiPAP)
        self.label_164.setGeometry(QtCore.QRect(190, 60, 101, 61))
        self.label_164.setStyleSheet("background-color: rgb(24, 6, 42);")
        self.label_164.setObjectName("label_164")
        self.label_165 = QtWidgets.QLabel(self.BiPAP)
        self.label_165.setGeometry(QtCore.QRect(820, 20, 71, 31))
        self.label_165.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_165.setObjectName("label_165")
        self.pushButton_61 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_61.setGeometry(QtCore.QRect(470, 10, 120, 120))
        self.pushButton_61.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_61.setText("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_61.clicked.connect(self.OxygeneConfig)

        self.pushButton_62 = QtWidgets.QPushButton(self.BiPAP)
        self.pushButton_62.setGeometry(QtCore.QRect(790, 10, 120, 120))
        self.pushButton_62.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.pushButton_62.setText("")
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_62.clicked.connect(self.IERatioConfig)

        self.label_168 = QtWidgets.QLabel(self.BiPAP)
        self.label_168.setGeometry(QtCore.QRect(250, 20, 41, 16))
        self.label_168.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_168.setObjectName("label_168")
        self.pushButton_57.raise_()
        self.pushButton_62.raise_()
        self.pushButton_61.raise_()
        self.pushButton_59.raise_()
        self.pushButton_60.raise_()
        self.label_150.raise_()
        self.label_151.raise_()
        self.label_152.raise_()
        self.label_153.raise_()
        self.label_154.raise_()
        self.pushButton_58.raise_()
        self.label_155.raise_()
        self.label_157.raise_()
        self.label_158.raise_()
        self.label_159.raise_()
        self.label_160.raise_()
        self.label_162.raise_()
        self.label_163.raise_()
        self.label_164.raise_()
        self.label_165.raise_()
        self.label_168.raise_()
        self.stackedWidget.addWidget(self.BiPAP)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setGeometry(QtCore.QRect(674, 10, 51, 41))
        self.pushButton_15.setStyleSheet("image: url(:/newPrefix/New folder/disable-alarm.png);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setGeometry(QtCore.QRect(740, 10, 51, 41))
        self.pushButton_16.setStyleSheet("image: url(:/newPrefix/New folder/icons8-alarm-96.png);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.AlarmsConfig)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(180, 340, 41, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(180, 240, 41, 41))
        self.label_18.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_18.setObjectName("label_18")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(180, 210, 41, 20))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(50, 465, 41, 21))
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(60, 620, 21, 21))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setGeometry(QtCore.QRect(180, 620, 31, 20))
        self.label_38.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.widget)
        self.label_39.setGeometry(QtCore.QRect(50, 340, 41, 21))
        self.label_39.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_3.setGeometry(QtCore.QRect(800, 0, 101, 61))
        self.stackedWidget_3.setStyleSheet("image: url(:/newPrefix/New folder/power_critical_light.png);\n"
"background-color: rgb(0, 0, 127);")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("image: url(:/newPrefix/New folder/power_battery_light.png);")
        self.page.setObjectName("page")
        self.stackedWidget_3.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("image: url(:/newPrefix/New folder/power_batteryCharging_light.png);")
        self.page_2.setObjectName("page_2")
        self.stackedWidget_3.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_3.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("image: url(:/newPrefix/New folder/power_wall_light.png);")
        self.page_4.setObjectName("page_4")
        self.stackedWidget_3.addWidget(self.page_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(1110, 610, 120, 120))
        self.pushButton_4.setStyleSheet("QPushButton{image: url(:/newPrefix/New folder/settings_light.gif);\n"
"\n"
"    color: white;\n"
"    background-color: rgb(58, 134, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.SettingsPage)

        self.stackedWidget.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_14.raise_()
        self.Trigger.raise_()
        self.comboBox.raise_()
        self.label_22.raise_()
        self.dateTimeEdit.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.lcdNumber_4.raise_()
        self.lcdNumber_5.raise_()
        self.lcdNumber_6.raise_()
        self.lcdNumber_7.raise_()
        self.lcdNumber_8.raise_()
        self.label_26.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.label_5.raise_()
        self.label_18.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_11.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.stackedWidget_3.raise_()
        self.pushButton_4.raise_()
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(370, 70, 47, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(330, 270, 41, 31))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(360, 470, 31, 31))
        self.label_25.setObjectName("label_25")
        self.widget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Pressure</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Flow</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Volume</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">I:E Ratio</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">PEEP</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">VT</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Flow</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">PIP</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\">cmH2O</p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">FiO2</span></p></body></html>"))
        self.comboBox.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "VCV"))
        self.comboBox.setItemText(1, _translate("Form", "PCV"))
        self.comboBox.setItemText(2, _translate("Form", "SIMV"))
        self.comboBox.setItemText(3, _translate("Form", "CPAP"))
        self.comboBox.setItemText(4, _translate("Form", "BiPAP"))
        self.enable.setText(_translate("Form", "Enable"))

        self.label_22.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">MODES</span></p></body></html>"))
        self.lcdNumber_4.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_26.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">:</span></p></body></html>"))
        self.label_40.setText(_translate("Form", "cmH2O"))
        self.label_41.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_42.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_43.setText(_translate("Form", "cmH20"))
        self.label_51.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_44.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RR</span></p></body></html>"))
        self.label_45.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_46.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_47.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_53.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">VT</span></p></body></html>"))
        self.label_54.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Pmax</span></p></body></html>"))
        self.label_56.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PEEP</span></p></body></html>"))
        self.label_57.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_58.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">FiO2</span></p></body></html>"))
        self.label_59.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_60.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_61.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_93.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_94.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_95.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_96.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PIP</span></p></body></html>"))
        self.label_97.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">FiO2</span></p></body></html>"))
        self.label_98.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_99.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Pmax</span></p></body></html>"))
        self.label_100.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PEEP</span></p></body></html>"))
        self.label_101.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RR</span></p></body></html>"))
        self.label_102.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_103.setText(_translate("Form", "cmH20"))
        self.label_104.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_105.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_106.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_107.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_108.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_111.setText(_translate("Form", "cmH2O"))
        self.label_112.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_113.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_114.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_115.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PS</span></p></body></html>"))
        self.label_116.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">FiO2</span></p></body></html>"))
        self.label_117.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_119.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PEEP</span></p></body></html>"))
        self.label_120.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RR</span></p></body></html>"))
        self.label_121.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_122.setText(_translate("Form", "cmH20"))
        self.label_124.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_125.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_126.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_127.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_128.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">VT</span></p></body></html>"))
        self.label_129.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_130.setText(_translate("Form", "cmH2O"))
        self.label_132.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_133.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_134.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">CPAP</span></p></body></html>"))
        self.label_135.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">FiO2</span></p></body></html>"))
        self.label_136.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_139.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RR</span></p></body></html>"))
        self.label_140.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_143.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_144.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_145.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_146.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_149.setText(_translate("Form", "cmH2O"))
        self.label_150.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_151.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_152.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_153.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">IPAP</span></p></body></html>"))
        self.label_154.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">FiO2</span></p></body></html>"))
        self.label_155.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_157.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">EPAP</span></p></body></html>"))
        self.label_158.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">RR</span></p></body></html>"))
        self.label_159.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_160.setText(_translate("Form", "cmH20"))
        self.label_162.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_163.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_164.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">...</span></p></body></html>"))
        self.label_165.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_168.setText(_translate("Form", "cmH2O"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">BPM</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Rate</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\">cmH20</p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\">mL</p></body></html>"))
        self.label_38.setText(_translate("Form", "<html><head/><body><p align=\"center\">%</p></body></html>"))
        self.label_39.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">sec</span></p></body></html>"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p align=\"center\">cmH20</p></body></html>"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p align=\"center\">L/min</p></body></html>"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p align=\"center\">ml</p></body></html>"))
from pyqtgraph import PlotWidget
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_GraphPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
