# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI 01-07\IERatioConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from Iratio import *




class Ui_IERatioConfig(object):
    def Inc(self):
        x=self.lcdNumber.value()
        if x<1 :
            x=x+0.5
            self.lcdNumber.setProperty("value", x)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber.display(x)
            self.label_5.setText(str(x))
            f=open("Iratio.py","w")
            f.write("Iratio="+str(x)+"\n")
            f.close
            if f.mode=='r':
                contents= f.read()
    def Dec(self):
        x=self.lcdNumber.value()
        if x>0.5:
            x=x-0.5
            self.lcdNumber.setProperty("value", x)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber.display
            self.label_5.setText(str(x))
            f=open("Iratio.py","w")
            f.write("\n"+"Iratio="+str(x))
            f.close
            if f.mode=='r':
                contents= f.read()

    def Inc2(self):
        y=self.lcdNumber_2.value()
        if y<4 :
            y=y+0.5
            self.lcdNumber_2.setProperty("value", y)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber_2.display(y)
            self.label_6.setText(str(y))
            f=open("Iratio.py","w")
            f.seek(100)
            f.write("\n"+"Eratio="+str(y))
            f.close
            if f.mode=='r':
                contents= f.read()
    def Dec2(self):
        y=self.lcdNumber_2.value()
        if y>1 :
            y=y-0.5
            self.lcdNumber_2.setProperty("value", y)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber_2.display(y)
            self.label_6.setText(str(y))
            f=open("Iratio.py","w")
            f.seek(100)
            f.write("Eratio="+str(y)+"\n")
            f.close
            if f.mode=='r':
                contents= f.read()
    def setupUi(self, IERatioConfig):
        IERatioConfig.setObjectName("IERatioConfig")
        IERatioConfig.resize(800, 600)
        IERatioConfig.setStyleSheet("  background: rgba(0, 128, 0, 0.3) /* Green background with 30% opacity */\n"
"")
        self.IE = QtWidgets.QFrame(IERatioConfig)
        self.IE.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.IE.setStyleSheet("QFrame {\n"
" background-color:#16a085;\n"
"    width: 20px;}\n"
"")
        self.IE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.IE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IE.setObjectName("IE")
        self.pushButton = QtWidgets.QPushButton(self.IE)
        self.pushButton.setGeometry(QtCore.QRect(650, 470, 91, 91))
        self.pushButton.setStyleSheet("image: url(:/newPrefix/New folder/back_light.png);\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda:IERatioConfig.close())

        self.label_3 = QtWidgets.QLabel(self.IE)
        self.label_3.setGeometry(QtCore.QRect(310, 20, 101, 41))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.IE)
        self.label_2.setGeometry(QtCore.QRect(280, 210, 121, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.IE)
        self.label_4.setGeometry(QtCore.QRect(290, 360, 121, 21))
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.IE)
        self.frame.setGeometry(QtCore.QRect(30, 30, 131, 111))
        self.frame.setStyleSheet("QFrame, QLabel, QToolTip {\n"
"      border: 2px solid green;\n"
"      border-radius: 4px;\n"
"      padding: 2px;\n"
"      background-image: url(images/welcome.png);\n"
"  }\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 31, 41))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 0, 91, 41))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 50, 31, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 21, 41))
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.IE)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 240, 71, 71))
        self.pushButton_4.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.Inc)

        self.pushButton_5 = QtWidgets.QPushButton(self.IE)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 240, 71, 71))
        self.pushButton_5.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.Dec)

        self.pushButton_12 = QtWidgets.QPushButton(self.IE)
        self.pushButton_12.setGeometry(QtCore.QRect(170, 380, 71, 71))
        self.pushButton_12.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.Dec2)

        self.pushButton_13 = QtWidgets.QPushButton(self.IE)
        self.pushButton_13.setGeometry(QtCore.QRect(450, 380, 71, 71))
        self.pushButton_13.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.Inc2)

        self.lcdNumber = QtWidgets.QLCDNumber(self.IE)
        self.lcdNumber.setGeometry(QtCore.QRect(290, 260, 121, 51))
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setProperty("value", Iratio)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.IE)
        self.lcdNumber_2.setGeometry(QtCore.QRect(280, 390, 131, 51))
        self.lcdNumber_2.setProperty("value", Eratio)
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.retranslateUi(IERatioConfig)
        QtCore.QMetaObject.connectSlotsByName(IERatioConfig)

    def retranslateUi(self, IERatioConfig):
        _translate = QtCore.QCoreApplication.translate
        IERatioConfig.setWindowTitle(_translate("IERatioConfig", "Form"))
        self.label_3.setText(_translate("IERatioConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">I:E Ratio</span></p></body></html>"))
        self.label_2.setText(_translate("IERatioConfig", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Inspiration Time</span></p></body></html>"))
        self.label_4.setText(_translate("IERatioConfig", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Expiration Time</span></p></body></html>"))
        self.label_5.setText(_translate("IERatioConfig", "<html><head/><body><p><span style=\" color:#ffffff;\">....</span></p></body></html>"))
        self.label.setText(_translate("IERatioConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">I:E Ratio</span></p></body></html>"))
        self.label_6.setText(_translate("IERatioConfig", "<html><head/><body><p><span style=\" color:#ffffff;\">....</span></p></body></html>"))
        self.label_7.setText(_translate("IERatioConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">:</span></p></body></html>"))
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IERatioConfig = QtWidgets.QWidget()
    ui = Ui_IERatioConfig()
    ui.setupUi(IERatioConfig)
    IERatioConfig.show()
    sys.exit(app.exec_())
