# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI 01-07\RRConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from rr import *

class Ui_RRConfig(object):
    def Inc(self):

        x=self.lcdNumber.intValue()
        if x<32 :
            x=x+1
            self.lcdNumber.setProperty("value", x)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber.display(x)
            self.label_5.setText(str(x))
            f=open("rr.py","w")
            f.write("rr="+str(x)+"\n")
            f.close
            if f.mode=='r':
                contents= f.read()

    def Dec(self):
        x=self.lcdNumber.intValue()
        if x>8 :
            x=x-1
            self.lcdNumber.setProperty("value", x)
        #self.lcdNumber.value=self.lcdNumber.value+0.5
            self.lcdNumber.display(x)
            self.label_5.setText(str(x))
            f=open("rr.py","w")
            f.write("rr="+str(x)+"\n")
            f.close
            if f.mode=='r':
                contents= f.read()
   

    def setupUi(self, RRConfig):
        RRConfig.setObjectName("RRConfig")
        RRConfig.resize(800, 600)
        RRConfig.setStyleSheet("background-color: rgb(206, 225, 254);")
        self.RRConfig_2 = QtWidgets.QFrame(RRConfig)
        self.RRConfig_2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.RRConfig_2.setStyleSheet("QFrame[height=\"3\"], QFrame[width=\"3\"] {\n"
"    background-color: #AAA;\n"
"}\n"
"")
        self.RRConfig_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RRConfig_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RRConfig_2.setObjectName("RRConfig_2")
        self.pushButton = QtWidgets.QPushButton(self.RRConfig_2)
        self.pushButton.setGeometry(QtCore.QRect(660, 470, 91, 91))
        self.pushButton.setStyleSheet("image: url(:/newPrefix/New folder/back_light.png);\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda:RRConfig.close())

        self.label_3 = QtWidgets.QLabel(self.RRConfig_2)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 211, 71))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.RRConfig_2)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 270, 91, 81))
        self.pushButton_2.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Dec)

        self.pushButton_3 = QtWidgets.QPushButton(self.RRConfig_2)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 270, 101, 81))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Inc)

        self.lcdNumber = QtWidgets.QLCDNumber(self.RRConfig_2)
        self.lcdNumber.setGeometry(QtCore.QRect(330, 280, 91, 51))
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setProperty("intValue", rr)
        self.lcdNumber.setObjectName("lcdNumber")
        self.frame = QtWidgets.QFrame(self.RRConfig_2)
        self.frame.setGeometry(QtCore.QRect(30, 30, 131, 111))
        self.frame.setStyleSheet("QFrame, QLabel, QToolTip {\n"
"      border: 2px solid green;\n"
"      border-radius: 4px;\n"
"      padding: 2px;\n"
"      background-image: url(images/welcome.png);\n"
"  }\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 61, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.RRConfig_2)
        self.label_2.setGeometry(QtCore.QRect(430, 290, 47, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(RRConfig)
        self.pushButton_3.clicked.connect(self.lcdNumber.setDecMode)
        self.pushButton_2.pressed.connect(self.lcdNumber.setDecMode)
        QtCore.QMetaObject.connectSlotsByName(RRConfig)

    def retranslateUi(self, RRConfig):
        _translate = QtCore.QCoreApplication.translate
        RRConfig.setWindowTitle(_translate("RRConfig", "Form"))
        self.label_3.setText(_translate("RRConfig", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Respiratory Rate </span></p></body></html>"))
        self.label_5.setText(_translate("RRConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">....</span></p></body></html>"))
        self.label.setText(_translate("RRConfig", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">RR</span></p></body></html>"))
        self.label_2.setText(_translate("RRConfig", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">BPM</span></p></body></html>"))
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RRConfig = QtWidgets.QWidget()
    ui = Ui_RRConfig()
    ui.setupUi(RRConfig)
    RRConfig.show()
    sys.exit(app.exec_())
