# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI 01-07\SettingsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GraphPage import *
from DefaultPage import *
from AlarmsConfig import *


class Ui_SettingsPage(object):
    def Inc(self):
        x=self.lcdNumber_2.intValue()
        if x<100 :
            x=self.lcdNumber_2.intValue()
            x=x+1
            self.lcdNumber_2.setProperty("value", x)
            self.lcdNumber_2.display(x)

            
    def Dec(self):
        x=self.lcdNumber_3.intValue()
        if x>0 :
            x=x-1
            self.lcdNumber_3.setProperty("value", x)
            self.lcdNumber_3.display(x)
    def Inc2(self):
        x=self.lcdNumber.intValue()
        if x<110 :
            x=self.lcdNumber.intValue()
            x=x+1
            self.lcdNumber.setProperty("value", x)
            self.lcdNumber.display(x)

            
    def Dec2(self):
        x=self.lcdNumber.intValue()
        if x>0 :
            x=x-1
            self.lcdNumber.setProperty("value", x)
            self.lcdNumber.display(x)
    def AlarmsConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_AlarmsConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def DefaultPage (self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_DefaultPage ()
        self.ui.setupUi(self.window)
        self.window.show()
    def GraphPage(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_GraphPage()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius:10px;\n"
"border:solid None rgb(255,255,255);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(480, 30, 161, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 140, 231, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(190, 230, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 330, 251, 51))
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 140, 201, 41))
        self.pushButton_5.setStyleSheet("QPushButton{ background-color:white;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
" }\n"
"\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(440, 310, 111, 111))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(560, 350, 47, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(1120, 660, 120, 120))
        self.pushButton_10.setStyleSheet("QPushButton{image: url(:/newPrefix/New folder/back_light.png);\n"
"\n"
"    color: white;\n"
"    background-color: rgb(58, 134, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(lambda:Form.close())

        self.Defaultview = QtWidgets.QPushButton(self.frame)
        self.Defaultview.setGeometry(QtCore.QRect(1120, 190, 120, 120))
        self.Defaultview.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/New folder/default_view_light.png);\n"
"\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:1, y1:0, x2:0.995, y2:1, stop:0 rgba(218, 218, 218, 255), stop:0.305419 rgba(0, 7, 11, 255), stop:0.935961 rgba(2, 11, 18, 255), stop:1 rgba(240, 240, 240, 255));\n"
"    border: 1px solid black;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.Defaultview.setText("")
        self.Defaultview.setObjectName("Defaultview")
        self.Graphview = QtWidgets.QPushButton(self.frame)
        self.Graphview.setGeometry(QtCore.QRect(1120, 350, 120, 120))
        self.Graphview.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 199, 0, 255), stop:1 rgba(192, 5, 67, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/graph_view_light.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.Graphview.setText("")
        self.Graphview.setObjectName("Graphview")
        self.Graphview.clicked.connect(self.GraphPage)
        self.Graphview.clicked.connect(lambda:Form.close())


        

        self.pushButton_20 = QtWidgets.QPushButton(self.frame)
        self.pushButton_20.setGeometry(QtCore.QRect(650, 200, 101, 91))
        self.pushButton_20.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.Inc)

        self.pushButton_21 = QtWidgets.QPushButton(self.frame)
        self.pushButton_21.setGeometry(QtCore.QRect(330, 210, 101, 91))
        self.pushButton_21.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(self.Dec)

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 320, 111, 101))
        self.pushButton_2.setStyleSheet("image: url(:/newPrefix/New folder/btn-remove-normal.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Dec2)

        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 320, 91, 101))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/New folder/btn-add-normal.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Inc2)

        self.alarms = QtWidgets.QPushButton(self.frame)
        self.alarms.setGeometry(QtCore.QRect(1120, 500, 120, 120))
        self.alarms.setStyleSheet("\n"
"QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/icons8-alarm-96.png);\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: green; }\n"
"")
        self.alarms.setText("")
        self.alarms.setObjectName("alarms")
        self.alarms.clicked.connect(self.AlarmsConfig)

        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setGeometry(QtCore.QRect(450, 190, 111, 111))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.frame)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(160, 40, 171, 31))
        self.dateTimeEdit_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.dateTimeEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateTimeEdit_2.setWrapping(False)
        self.dateTimeEdit_2.setDate(QtCore.QDate(2021, 7, 4))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.stackedWidget_2.setStyleSheet("image: url(:/newPrefix/New folder/power_critical_light.png);\n"
"background-color: rgb(0, 0, 127);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("image: url(:/newPrefix/New folder/power_battery_light.png);")
        self.page_5.setObjectName("page_5")
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("image: url(:/newPrefix/New folder/power_batteryCharging_light.png);")
        self.page_6.setObjectName("page_6")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setStyleSheet("image: url(:/newPrefix/New folder/power_wall_light.png);")
        self.page_8.setObjectName("page_8")
        self.stackedWidget_2.addWidget(self.page_8)
        self.trigger = QtWidgets.QPushButton(self.frame)
        self.trigger.setGeometry(QtCore.QRect(1120, 40, 120, 120))
        self.trigger.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(10, 242, 251, 255), stop:1 rgba(224, 6, 159, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/trigger_light.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.trigger.setText("")
        self.trigger.setObjectName("trigger")
        self.trigger.clicked.connect(self.DefaultPage)


        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 450, 251, 51))
        self.label_6.setObjectName("label_6")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame)
        self.dateTimeEdit.setGeometry(QtCore.QRect(320, 450, 411, 61))
        self.dateTimeEdit.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(130, 740, 131, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(450, 740, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(700, 740, 151, 31))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 610, 120, 120))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 199, 0, 255), stop:1 rgba(192, 5, 67, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/icons8-restore-window-96.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 610, 120, 120))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 199, 0, 255), stop:1 rgba(192, 5, 67, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/battery.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 610, 120, 120))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color:qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 199, 0, 255), stop:1 rgba(192, 5, 67, 255));\n"
"    border-radius: 20px;\n"
"image: url(:/newPrefix/New folder/volume.png);\n"
"\n"
"}\n"
"QPushButton:pressed{ background-color: orange; }\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Settings</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Default Patient Configuration</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Brightness</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Alarm Silence /Reset Time </span></p></body></html>"))
        self.pushButton_5.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Save current configuration</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "Save current configuration"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">sec</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Time and Date</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Battery Status</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Sound </span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Factory Settings</span></p></body></html>"))
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_SettingsPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
