# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\OneDrive\Bureau\new HMI\DefaultPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from InspirationConfig import *
from IERatioConfig import *
from TidalVolumeConfig import *
from ExpirationConfig import *
from RRConfig import *
from OxygeneConfig import *
from TriggerPressureConfig import *

from PyQt5.QtWidgets import QWidget   


class Ui_Form(QWidget):
    def InspirationConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_InspirationConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def IERatioConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_IERatioConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def TidalVolumeConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui =Ui_TidalVolumeConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def ExpirationConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_ExpirationConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def RRConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_RRConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def TriggerPressureConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_TriggerPressureConfig()
        self.ui.setupUi(self.window)
        self.window.show()
    def OxygeneConfig(self):
        self.window=QtWidgets.QWidget()
        self.ui = Ui_OxygeneConfig()
        self.ui.setupUi(self.window)
        self.window.show()    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(710, 400, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(200, 255, 255);\"\n"
"                                \"border-width: 1;\"\n"
"                                \"border-radius: 3;\"\n"
"                                \"border-style: solid;\"\n"
"                                \"border-color: rgb(10, 10, 10)}\"\n"
"\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Graph = QtWidgets.QPushButton(self.frame)
        self.Graph.setGeometry(QtCore.QRect(1060, 260, 111, 91))
        self.Graph.setStyleSheet("QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/graph_view_light.png);\n"
"\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}")
        self.Graph.setText("")
        self.Graph.setObjectName("Graph")
        self.Trigger = QtWidgets.QPushButton(self.frame)
        self.Trigger.setGeometry(QtCore.QRect(1060, 120, 111, 111))
        self.Trigger.setStyleSheet("\n"
"QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/trigger_light.png);\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}")
        self.Trigger.setText("")
        self.Trigger.setObjectName("Trigger")
        self.Start = QtWidgets.QPushButton(self.frame)
        self.Start.setGeometry(QtCore.QRect(1060, 380, 111, 91))
        self.Start.setStyleSheet("QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/start_light.png);\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}")
        self.Start.setText("")
        self.Start.setObjectName("Start")
        self.InspirationPressure = QtWidgets.QPushButton(self.frame)
        self.InspirationPressure.setGeometry(QtCore.QRect(79, 160, 161, 150))
        self.InspirationPressure.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.InspirationPressure.setText("")
        self.InspirationPressure.setObjectName("InspirationPressure")
        self.InspirationPressure.clicked.connect(self.InspirationConfig)

        self.IERatio = QtWidgets.QPushButton(self.frame)
        self.IERatio.setGeometry(QtCore.QRect(280, 160, 150, 150))
        self.IERatio.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.IERatio.setText("")
        self.IERatio.setObjectName("IERatio")
        self.IERatio.clicked.connect(self.IERatioConfig)

        self.TidalVolume = QtWidgets.QPushButton(self.frame)
        self.TidalVolume.setGeometry(QtCore.QRect(460, 160, 150, 150))
        self.TidalVolume.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.TidalVolume.setText("")
        self.TidalVolume.setObjectName("TidalVolume")
        self.TidalVolume.clicked.connect(self.TidalVolumeConfig)

        self.ExpirationPressure = QtWidgets.QPushButton(self.frame)
        self.ExpirationPressure.setGeometry(QtCore.QRect(79, 360, 161, 150))
        self.ExpirationPressure.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.ExpirationPressure.setText("")
        self.ExpirationPressure.setObjectName("ExpirationPressure")
        self.ExpirationPressure.clicked.connect(self.ExpirationConfig)

        self.BPM = QtWidgets.QPushButton(self.frame)
        self.BPM.setGeometry(QtCore.QRect(280, 360, 150, 150))
        self.BPM.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.BPM.setText("")
        self.BPM.setObjectName("BPM")
        self.BPM.clicked.connect(self.RRConfig)


        

        self.Flow = QtWidgets.QPushButton(self.frame)
        self.Flow.setGeometry(QtCore.QRect(460, 360, 150, 150))
        self.Flow.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.Flow.setText("")
        self.Flow.setObjectName("Flow")

        self.Settings = QtWidgets.QPushButton(self.frame)
        self.Settings.setGeometry(QtCore.QRect(1060, 510, 111, 101))
        self.Settings.setStyleSheet("QPushButton\n"
"\n"
"{image: url(:/newPrefix/New folder/settings_light.gif);\n"
"\n"
"\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"border-style: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"\n"
"{\n"
"\n"
"border-style: solid;\n"
"\n"
"border-color:grey;\n"
"\n"
"border-width: 2px;\n"
"\n"
"}")
        self.Settings.setText("")
        self.Settings.setObjectName("Settings")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(520, 30, 371, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 180, 141, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 270, 61, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(320, 180, 81, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(480, 180, 101, 31))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(510, 280, 41, 21))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(90, 380, 141, 31))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 470, 51, 21))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(330, 460, 61, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(510, 370, 51, 31))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(500, 470, 61, 31))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.Oxygene = QtWidgets.QPushButton(self.frame)
        self.Oxygene.setGeometry(QtCore.QRect(650, 160, 161, 150))
        self.Oxygene.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.Oxygene.setText("")
        self.Oxygene.setObjectName("Oxygene")
        self.Oxygene.clicked.connect(self.OxygeneConfig)

        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(680, 180, 81, 31))
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(740, 240, 21, 21))
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 20, 120, 80))
        self.frame_2.setStyleSheet("image: url(:/newPrefix/New folder/power_batteryCharging_light.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(140, 40, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(300, 370, 121, 31))
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(110, 230, 91, 31))
        self.label_17.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(320, 230, 81, 31))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(496, 230, 71, 31))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(676, 230, 61, 41))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(120, 420, 81, 41))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(330, 420, 71, 31))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(490, 410, 81, 41))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(660, 380, 141, 31))
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.Ptrig = QtWidgets.QPushButton(self.frame)
        self.Ptrig.setGeometry(QtCore.QRect(649, 360, 161, 150))
        self.Ptrig.setStyleSheet("QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(60, 186, 162, 255), stop:1 rgba(98, 211, 162, 255))\n"
"}\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.Ptrig.setText("")
        self.Ptrig.setObjectName("Ptrig")
        self.Ptrig.clicked.connect(self.TriggerPressureConfig)

        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(686, 412, 71, 41))
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(690, 470, 61, 21))
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(660, 370, 121, 31))
        self.label_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.Trigger.raise_()
        self.Graph.raise_()
        self.Start.raise_()
        self.InspirationPressure.raise_()
        self.IERatio.raise_()
        self.TidalVolume.raise_()
        self.ExpirationPressure.raise_()
        self.BPM.raise_()
        self.Flow.raise_()
        self.Settings.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.Oxygene.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.frame_2.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.Ptrig.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">StarzMed Air-7000</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Inspiration Pressure</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">cmH20</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">I:E Ratio</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Tidal Volume</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">ml</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">PEEP</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">cmH20</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">BPM</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Flow</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">L/min</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Oxygen</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p>%</p></body></html>"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Respiratory Rate</span></p></body></html>"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Inspiration Pressure</span></p></body></html>"))
        self.label_26.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">cmH20</span></p></body></html>"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Ptrig(Sensitivity)</span></p></body></html>"))
import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
